require('dotenv').config({ path: require('path').join(__dirname, '.env') });
const pool = require('./src/config/db');

async function fix() {
  const conn = await pool.getConnection();
  try {
    await conn.beginTransaction();

    const tables = [
      `CREATE TABLE IF NOT EXISTS invoices (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, branch_id INT NULL, client_id INT NULL, quotation_id INT NULL, sales_order_id INT NULL, invoice_number VARCHAR(50) NOT NULL, subtotal DECIMAL(12,2) DEFAULT 0.00, total_amount DECIMAL(12,2) NOT NULL, discount_amount DECIMAL(12,2) DEFAULT 0.00, tax_amount DECIMAL(12,2) DEFAULT 0.00, shipping_cost DECIMAL(12,2) DEFAULT 0.00, paid_amount DECIMAL(12,2) DEFAULT 0.00, status VARCHAR(50) DEFAULT 'Draft', due_date DATE NULL, notes TEXT NULL, terms TEXT NULL, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS invoice_items (id INT AUTO_INCREMENT PRIMARY KEY, invoice_id INT NOT NULL, product_id INT NULL, description VARCHAR(255) NOT NULL, quantity DECIMAL(10,2) DEFAULT 1, unit_price DECIMAL(12,2) DEFAULT 0.00, discount_percent DECIMAL(5,2) DEFAULT 0.00, tax_percent DECIMAL(5,2) DEFAULT 0.00, total DECIMAL(12,2) DEFAULT 0.00, FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS recurring_invoices (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, customer_id INT NOT NULL, frequency VARCHAR(50) NOT NULL, start_date DATE NOT NULL, end_date DATE NULL, next_generate_date DATE NULL, total DECIMAL(12,2) DEFAULT 0.00, status VARCHAR(50) DEFAULT 'active', created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS payments (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, branch_id INT NULL, invoice_id INT NULL, customer_id INT NULL, vendor_id INT NULL, payment_number VARCHAR(50) NOT NULL, payment_date DATE NOT NULL, amount DECIMAL(12,2) NOT NULL, payment_method VARCHAR(50) DEFAULT 'cash', reference_number VARCHAR(100) NULL, bank_account_id INT NULL, cheque_number VARCHAR(100) NULL, notes TEXT NULL, status VARCHAR(50) DEFAULT 'completed', created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS credit_notes (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, customer_id INT NOT NULL, invoice_id INT NULL, credit_note_number VARCHAR(50) NOT NULL, date DATE NOT NULL, amount DECIMAL(12,2) NOT NULL, reason TEXT NULL, status VARCHAR(50) DEFAULT 'open', created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS debit_notes (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, vendor_id INT NULL, purchase_invoice_id INT NULL, debit_note_number VARCHAR(50) NOT NULL, date DATE NOT NULL, amount DECIMAL(12,2) NOT NULL, reason TEXT NULL, status VARCHAR(50) DEFAULT 'open', created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS refunds (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, customer_id INT NOT NULL, invoice_id INT NULL, payment_id INT NULL, refund_number VARCHAR(50) NOT NULL, date DATE NOT NULL, amount DECIMAL(12,2) NOT NULL, reason TEXT NULL, status VARCHAR(50) DEFAULT 'pending', created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS purchase_orders (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, branch_id INT NULL, vendor_id INT NOT NULL, order_number VARCHAR(50) NOT NULL, order_date DATE NOT NULL, expected_date DATE NULL, subtotal DECIMAL(12,2) DEFAULT 0.00, discount_amount DECIMAL(12,2) DEFAULT 0.00, tax_amount DECIMAL(12,2) DEFAULT 0.00, total DECIMAL(12,2) DEFAULT 0.00, status VARCHAR(50) DEFAULT 'pending', notes TEXT NULL, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS purchase_order_items (id INT AUTO_INCREMENT PRIMARY KEY, purchase_order_id INT NOT NULL, product_id INT NULL, description VARCHAR(255) NOT NULL, quantity DECIMAL(10,2) DEFAULT 1, unit_price DECIMAL(12,2) DEFAULT 0.00, tax_percent DECIMAL(5,2) DEFAULT 0.00, total DECIMAL(12,2) DEFAULT 0.00, received_quantity DECIMAL(10,2) DEFAULT 0, FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS purchase_invoices (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, branch_id INT NULL, vendor_id INT NOT NULL, purchase_order_id INT NULL, invoice_number VARCHAR(50) NOT NULL, invoice_date DATE NOT NULL, due_date DATE NULL, subtotal DECIMAL(12,2) DEFAULT 0.00, tax_amount DECIMAL(12,2) DEFAULT 0.00, total DECIMAL(12,2) DEFAULT 0.00, paid_amount DECIMAL(12,2) DEFAULT 0.00, status VARCHAR(50) DEFAULT 'unpaid', notes TEXT NULL, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS purchase_invoice_items (id INT AUTO_INCREMENT PRIMARY KEY, purchase_invoice_id INT NOT NULL, product_id INT NULL, description VARCHAR(255) NOT NULL, quantity DECIMAL(10,2) DEFAULT 1, unit_price DECIMAL(12,2) DEFAULT 0.00, tax_percent DECIMAL(5,2) DEFAULT 0.00, total DECIMAL(12,2) DEFAULT 0.00, FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoices(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS purchase_returns (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, vendor_id INT NOT NULL, purchase_invoice_id INT NULL, return_number VARCHAR(50) NOT NULL, return_date DATE NOT NULL, total DECIMAL(12,2) DEFAULT 0.00, reason TEXT NULL, status VARCHAR(50) DEFAULT 'pending', created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS chart_of_accounts (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, account_code VARCHAR(50) NOT NULL, account_name VARCHAR(200) NOT NULL, account_type VARCHAR(50) NOT NULL, parent_id INT NULL, balance DECIMAL(14,2) DEFAULT 0.00, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS transactions (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, branch_id INT NULL, transaction_number VARCHAR(50) NOT NULL, type VARCHAR(50) NOT NULL, category VARCHAR(100) NULL, account_id INT NULL, bank_account_id INT NULL, amount DECIMAL(12,2) NOT NULL, date DATE NOT NULL, reference VARCHAR(255) NULL, description TEXT NULL, payment_method VARCHAR(50) NULL, cheque_number VARCHAR(100) NULL, module_type VARCHAR(50) NULL, module_id INT NULL, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS bank_accounts (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, bank_name VARCHAR(200) NOT NULL, account_holder VARCHAR(200) NULL, account_number VARCHAR(100) NOT NULL, ifsc_code VARCHAR(50) NULL, branch VARCHAR(150) NULL, opening_balance DECIMAL(12,2) DEFAULT 0.00, current_balance DECIMAL(12,2) DEFAULT 0.00, status VARCHAR(20) DEFAULT 'active', created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS account_categories (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(150) NOT NULL, type VARCHAR(50) NOT NULL, parent_id INT NULL, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS tax_rates (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(100) NOT NULL, rate DECIMAL(5,2) NOT NULL, type VARCHAR(50) DEFAULT 'GST', is_inclusive TINYINT(1) DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS units (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(100) NOT NULL, short_name VARCHAR(20) NOT NULL, base_unit_id INT NULL, conversion_factor DECIMAL(10,4) DEFAULT 1, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS product_categories (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(150) NOT NULL, parent_id INT NULL, image_url TEXT NULL, description TEXT NULL, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS brands (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(150) NOT NULL, logo_url TEXT NULL, description TEXT NULL, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS products (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(255) NOT NULL, sku VARCHAR(100) NULL, barcode VARCHAR(100) NULL, category_id INT NULL, brand_id INT NULL, unit_id INT NULL, type VARCHAR(50) DEFAULT 'goods', description TEXT NULL, purchase_price DECIMAL(12,2) DEFAULT 0.00, selling_price DECIMAL(12,2) DEFAULT 0.00, tax_percent DECIMAL(5,2) DEFAULT 0.00, opening_stock DECIMAL(10,2) DEFAULT 0, current_stock DECIMAL(10,2) DEFAULT 0, minimum_stock DECIMAL(10,2) DEFAULT 0, maximum_stock DECIMAL(10,2) DEFAULT 0, warehouse_id INT NULL, has_batch TINYINT(1) DEFAULT 0, has_serial TINYINT(1) DEFAULT 0, image_url TEXT NULL, status VARCHAR(20) DEFAULT 'active', created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS warehouses (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(200) NOT NULL, code VARCHAR(50) NULL, address TEXT NULL, city VARCHAR(100) NULL, manager_id INT NULL, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS stock (id INT AUTO_INCREMENT PRIMARY KEY, product_id INT NOT NULL, warehouse_id INT NOT NULL, quantity DECIMAL(10,2) DEFAULT 0, reserved_quantity DECIMAL(10,2) DEFAULT 0, batch_number VARCHAR(100) NULL, serial_number VARCHAR(100) NULL, expiry_date DATE NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE, FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS stock_transfers (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, from_warehouse_id INT NOT NULL, to_warehouse_id INT NOT NULL, product_id INT NOT NULL, quantity DECIMAL(10,2) NOT NULL, transfer_date DATE NOT NULL, status VARCHAR(50) DEFAULT 'pending', notes TEXT NULL, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS stock_adjustments (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, warehouse_id INT NOT NULL, product_id INT NOT NULL, adjustment_type VARCHAR(50) NOT NULL, quantity DECIMAL(10,2) NOT NULL, reason TEXT NULL, adjustment_date DATE NOT NULL, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS employees (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, branch_id INT NULL, user_id INT NULL, employee_code VARCHAR(50) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(50) NULL, department_id INT NULL, designation_id INT NULL, date_of_joining DATE NULL, date_of_birth DATE NULL, gender VARCHAR(20) NULL, address TEXT NULL, emergency_contact VARCHAR(100) NULL, emergency_phone VARCHAR(50) NULL, bank_name VARCHAR(150) NULL, bank_account VARCHAR(100) NULL, ifsc_code VARCHAR(50) NULL, basic_salary DECIMAL(12,2) DEFAULT 0.00, status VARCHAR(20) DEFAULT 'active', created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS employee_attendance (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, employee_id INT NOT NULL, date DATE NOT NULL, clock_in DATETIME NULL, clock_out DATETIME NULL, total_hours DECIMAL(5,2) DEFAULT 0, status VARCHAR(50) DEFAULT 'present', notes TEXT NULL, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE, UNIQUE KEY unique_emp_date (employee_id, date))`,
      `CREATE TABLE IF NOT EXISTS leave_types (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(100) NOT NULL, days_per_year INT DEFAULT 0, is_paid TINYINT(1) DEFAULT 1, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS leave_requests (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, employee_id INT NOT NULL, leave_type_id INT NOT NULL, from_date DATE NOT NULL, to_date DATE NOT NULL, days INT NOT NULL, reason TEXT NULL, status VARCHAR(50) DEFAULT 'pending', approved_by INT NULL, approved_at DATETIME NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS payroll (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, employee_id INT NOT NULL, month INT NOT NULL, year INT NOT NULL, basic_salary DECIMAL(12,2) DEFAULT 0.00, allowances DECIMAL(12,2) DEFAULT 0.00, deductions DECIMAL(12,2) DEFAULT 0.00, tax DECIMAL(12,2) DEFAULT 0.00, net_salary DECIMAL(12,2) DEFAULT 0.00, payment_status VARCHAR(50) DEFAULT 'unpaid', paid_at DATETIME NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS performance_reviews (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, employee_id INT NOT NULL, reviewer_id INT NOT NULL, review_period VARCHAR(50) NULL, rating INT DEFAULT 0, strengths TEXT NULL, improvements TEXT NULL, goals TEXT NULL, comments TEXT NULL, status VARCHAR(50) DEFAULT 'draft', review_date DATE NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS employee_documents (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, employee_id INT NOT NULL, document_type VARCHAR(100) NOT NULL, document_name VARCHAR(255) NOT NULL, file_url TEXT NOT NULL, expiry_date DATE NULL, notes TEXT NULL, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS milestones (id INT AUTO_INCREMENT PRIMARY KEY, project_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NULL, due_date DATE NULL, status VARCHAR(50) DEFAULT 'pending', progress INT DEFAULT 0, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS subtasks (id INT AUTO_INCREMENT PRIMARY KEY, task_id INT NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(50) DEFAULT 'pending', assigned_to INT NULL, due_date DATE NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS timesheets (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, employee_id INT NOT NULL, project_id INT NULL, task_id INT NULL, date DATE NOT NULL, hours DECIMAL(5,2) NOT NULL, description TEXT NULL, status VARCHAR(50) DEFAULT 'pending', approved_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS knowledge_base (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, category VARCHAR(150) NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, tags TEXT NULL, views INT DEFAULT 0, helpful_count INT DEFAULT 0, is_published TINYINT(1) DEFAULT 1, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS sla_policies (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(150) NOT NULL, priority VARCHAR(50) NOT NULL, first_response_hours INT DEFAULT 4, resolution_hours INT DEFAULT 24, business_hours_only TINYINT(1) DEFAULT 1, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS email_campaigns (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, content LONGTEXT NULL, recipient_list TEXT NULL, scheduled_at DATETIME NULL, sent_at DATETIME NULL, status VARCHAR(50) DEFAULT 'draft', total_sent INT DEFAULT 0, total_opened INT DEFAULT 0, total_clicked INT DEFAULT 0, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS sms_campaigns (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(255) NOT NULL, message TEXT NOT NULL, recipient_list TEXT NULL, scheduled_at DATETIME NULL, sent_at DATETIME NULL, status VARCHAR(50) DEFAULT 'draft', total_sent INT DEFAULT 0, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS whatsapp_campaigns (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(255) NOT NULL, message TEXT NOT NULL, template_name VARCHAR(255) NULL, recipient_list TEXT NULL, scheduled_at DATETIME NULL, sent_at DATETIME NULL, status VARCHAR(50) DEFAULT 'draft', total_sent INT DEFAULT 0, created_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS documents (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, branch_id INT NULL, module_type VARCHAR(50) NULL, module_id INT NULL, category VARCHAR(100) NULL, name VARCHAR(255) NOT NULL, file_url TEXT NOT NULL, file_size INT DEFAULT 0, file_type VARCHAR(50) NULL, description TEXT NULL, expiry_date DATE NULL, is_archived TINYINT(1) DEFAULT 0, uploaded_by INT NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS notifications (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NULL, type VARCHAR(50) DEFAULT 'info', module_type VARCHAR(50) NULL, module_id INT NULL, is_read TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS message_templates (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(150) NOT NULL, type VARCHAR(50) NOT NULL, subject VARCHAR(255) NULL, body TEXT NOT NULL, variables TEXT NULL, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS audit_logs (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NULL, user_id INT NULL, action VARCHAR(255) NOT NULL, module VARCHAR(100) NULL, record_id INT NULL, old_values TEXT NULL, new_values TEXT NULL, ip_address VARCHAR(50) NULL, user_agent TEXT NULL, created_at TIMESTAMP DEFAULT NOW())`,
      `CREATE TABLE IF NOT EXISTS ip_logs (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, ip_address VARCHAR(50) NOT NULL, location VARCHAR(255) NULL, device VARCHAR(255) NULL, browser VARCHAR(100) NULL, os VARCHAR(100) NULL, login_at TIMESTAMP DEFAULT NOW(), logout_at DATETIME NULL, is_successful TINYINT(1) DEFAULT 1)`,
      `CREATE TABLE IF NOT EXISTS user_sessions (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, token_hash VARCHAR(255) NOT NULL, ip_address VARCHAR(50) NULL, user_agent TEXT NULL, last_active TIMESTAMP DEFAULT NOW(), expires_at DATETIME NOT NULL, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS automation_rules (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, name VARCHAR(255) NOT NULL, trigger_module VARCHAR(100) NOT NULL, trigger_event VARCHAR(100) NOT NULL, conditions TEXT NULL, actions TEXT NULL, is_active TINYINT(1) DEFAULT 1, last_run_at DATETIME NULL, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
      `CREATE TABLE IF NOT EXISTS reminders (id INT AUTO_INCREMENT PRIMARY KEY, company_id INT NOT NULL, user_id INT NOT NULL, module_type VARCHAR(50) NOT NULL, module_id INT NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NULL, remind_at DATETIME NOT NULL, is_sent TINYINT(1) DEFAULT 0, is_read TINYINT(1) DEFAULT 0, created_at TIMESTAMP DEFAULT NOW(), FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE)`,
    ];

    for (const sql of tables) {
      await conn.execute(sql);
    }

    // Seed defaults
    await conn.execute("INSERT IGNORE INTO branches (id, company_id, name, code, city, state) VALUES (1, 1, 'Head Office - Mumbai', 'HO-MUM', 'Mumbai', 'Maharashtra')");
    await conn.execute("INSERT IGNORE INTO departments (id, company_id, name) VALUES (1, 1, 'Technology'),(2, 1, 'Sales'),(3, 1, 'Marketing'),(4, 1, 'HR'),(5, 1, 'Finance'),(6, 1, 'Support')");
    await conn.execute("INSERT IGNORE INTO designations (id, company_id, name, level) VALUES (1, 1, 'CEO', 1),(2, 1, 'Manager', 3),(3, 1, 'Team Lead', 4),(4, 1, 'Developer', 6),(5, 1, 'Sales Executive', 6)");
    await conn.execute("INSERT IGNORE INTO leave_types (id, company_id, name, days_per_year, is_paid) VALUES (1, 1, 'Casual Leave', 12, 1),(2, 1, 'Sick Leave', 12, 1),(3, 1, 'Earned Leave', 15, 1)");
    await conn.execute("INSERT IGNORE INTO tax_rates (id, company_id, name, rate, type) VALUES (1, 1, 'GST 5%', 5, 'GST'),(2, 1, 'GST 12%', 12, 'GST'),(3, 1, 'GST 18%', 18, 'GST'),(4, 1, 'GST 28%', 28, 'GST')");
    await conn.execute("INSERT IGNORE INTO units (id, company_id, name, short_name) VALUES (1, 1, 'Piece', 'Pc'),(2, 1, 'Kilogram', 'Kg'),(3, 1, 'Litre', 'L'),(4, 1, 'Hour', 'Hr')");
    await conn.execute("INSERT IGNORE INTO account_categories (id, company_id, name, type) VALUES (1, 1, 'Sales Income', 'income'),(2, 1, 'Rent', 'expense'),(3, 1, 'Salaries', 'expense')");

    await conn.commit();
    console.log('All tables created and seeded!');
    process.exit(0);
  } catch (err) {
    await conn.rollback();
    console.error('Error:', err.message);
    process.exit(1);
  } finally {
    conn.release();
  }
}
fix();
